"""initial migration

Revision ID: 5620f703c1d2
Revises:
Create Date: 2022-10-08 15:46:55.787852

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "5620f703c1d2"
down_revision = None
branch_labels = None
depends_on = None


ticker_names = [f"ticker_{i}" if i >= 10 else f"ticker_0{i}" for i in range(100)]


def create_tickers() -> None:
    tickers_table = table(
        "tickers",
        column("name"),
    )
    op.bulk_insert(
        tickers_table,
        [{"name": ticker_name} for ticker_name in ticker_names],
    )


def create_ticker_values() -> None:
    ticker_values_table = table(
        "ticker_values",
        column("value"),
        column("ticker_id"),
    )
    op.bulk_insert(
        ticker_values_table,
        [{"value": 0, "ticker_id": i + 1} for i in range(len(ticker_names))],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickers_id"), "tickers", ["id"], unique=False)
    op.create_index(op.f("ix_tickers_name"), "tickers", ["name"], unique=True)
    op.create_table(
        "ticker_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("ticker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticker_values_id"), "ticker_values", ["id"], unique=False)
    create_tickers()
    create_ticker_values()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_values_id"), table_name="ticker_values")
    op.drop_table("ticker_values")
    op.drop_index(op.f("ix_tickers_name"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_id"), table_name="tickers")
    op.drop_table("tickers")
    # ### end Alembic commands ###
